### ISSUE TITLE
error decoding response body

### ISSUE THREAD

**Issue by dr3s** [mdegans/misanthropic#12]
When I use your released crate with `Model::Sonnet35`, get the following error:
`HTTP error: error decoding response body`

```
unknown variant `claude-3-5-sonnet-20241022`, expected one of `claude-3-5-sonnet-latest`, `claude-3-5-sonnet-20240620`, `claude-3-sonnet-20241022`, `claude-3-opus-latest`, `claude-3-opus-20240229`, `claude-3-sonnet-20240229`, `claude-3-5-haiku-latest`, `claude-3-5-haiku-20241022`, `claude-3-haiku-20240307`, `claude-3-haiku-latest`
```

Model is too strict on de-serialization as `latest` variants will reply with the actual specific variant used.  In this case "claude-3-5-sonnet-20241022".

Model should really be a string on Message I think and the enum should just be a helper to construct it.

**Comment by mdegans** [comment]
> When I use your released crate with `Model::Sonnet35`, get the following error: `HTTP error: error decoding response body`
> 
> ```
> unknown variant `claude-3-5-sonnet-20241022`, expected one of `claude-3-5-sonnet-latest`, `claude-3-5-sonnet-20240620`, `claude-3-sonnet-20241022`, `claude-3-opus-latest`, `claude-3-opus-20240229`, `claude-3-sonnet-20240229`, `claude-3-5-haiku-latest`, `claude-3-5-haiku-20241022`, `claude-3-haiku-20240307`, `claude-3-haiku-latest`
> ```
> 
> Model is too strict on de-serialization as `latest` variants will reply with the actual specific variant used. In this case "claude-3-5-sonnet-20241022".
> 
> Model should really be a string on Message I think and the enum should just be a helper to construct it.

The reason is to avoid allocations unless necessary. It's not a big deal but it's one more `String`. What I'll probably do is make a `Custom` variant with a string.

As far as your PR goes, I'll merge it into the dev branch, add some tests for each `Model` variant to ensure this doesn't happen again, probably a `Custom` variant, and have a patch version by EOW at the latest. Thank you for the report and contribution.

**Comment by mdegans** [comment]
@dr3s I decided to make a `Custom` variant a `0.6` feature since it's a breaking change. `Model` is `Copy` and if I put a `String` in there, It can (well, should) no longer be `Copy`. There is a fair amount of code the assumes `Model` to be copy outside in and outside this codebase.

In the meantime, `Client::message` supports anything serializable, so if you need to use a custom model, (or customize the request json in general), you can use the `json` macro as shown in the `website_wizard.rs` example. Both `Client::stream` and `Client::message` support use like this:

```rust
...
    // Request a streaming completion. `json!` can be used, the concrete type,
    // `Request` or a combination of strings and concrete types like `Model`.
    // Client request methods accept anything serializable.
    let stream = client
        .stream(json!({
          "model": Model::Sonnet35, // String can go here
          "max_tokens": args.max_tokens,
          "temperature": 0,
          "system": args.system,
          "messages": [
            {
              "role": Role::User,
              "content": specs,
            }
          ],
        }))
        .await?
        // Filter out rate limit and overloaded errors. This is optional but
        // recommended for most use cases. The stream will continue when the
        // server is ready. Otherwise the stream will include these errors.
        .filter_rate_limit()
        // Filter out everything but text pieces (and errors).
        .text();
...
```

Edit: But yes, the response will fail, now that I think about it. So definitely adding a `Custom` variant in `0.6`.

**Comment by dr3s** [comment]
Yeah it's the message parsing and I was struggling with reading as Value. But I'm good with the dev branch and 0.5.1.

**Comment by mdegans** [comment]
@dr3s `0.5.1` Is now in main, tagged, here and on `crates.io`. You should be good to go for now.

Likely next week i'll drop 0.6 with very minor changes. Will include support for custom model names since you're absolutely right there's a need for it, even if I'm very diligent updating `Models`.
